### ISSUE TITLE
Listen to multiple Topics

### ISSUE THREAD

**Issue by mark--** [edenhill/kafkacat#179]
It would be nice if kafkacat could listen to multiple or all topics, e.g. with
`kafkacat -t topica,topicb` or `kafkcat -t *`

**Comment by edenhill** [comment]
Use `-G <unique-group.id>`.
Wildcards are supported by regexp when prefixing the expression with ^, e.g.:
`kafkacat -b mybroker -G my-group my-topic ^my-regex-.*-topic some-other-topic`

**Comment by mark--** [comment]
Thank you, it works! Did not see it in the docs.

**Comment by sangeet259** [comment]
Hi @edenhill , sorry for the tag but I tried this and it didn't work for me.

This is what I am doing individually for each topic which works:
```
docker run -d --network plaintext_default \
--name kcat edenhill/kcat:1.7.1 \
-b broker:9092 -C -t CUSTOMER-e -s avro -r http://schema-registry:8081 -q > /dev/null
```
and then read using `docker logs kcat >> output.log`. This works fine. ✅

But the problem is I have to do this for 10 topics in a loop. So it kinda takes a lot of time.

I wanted to try the solution mentioned here.

I first tried this on one topic:
```
docker run --network plaintext_default \
--name kcat edenhill/kcat:1.7.1 \
-b broker:9092 -C  -e -s avro \
-r http://schema-registry:8081 -q \
-G abc CUSTOMER
```
this showed nothing in the `docker logs kcat`
And the same with specifying multiple topics

```
docker run --network plaintext_default \
--name kcat edenhill/kcat:1.7.1 \
-b broker:9092 -C  -e -s avro \
-r http://schema-registry:8081 -q \
-G abc CUSTOMER WAREHOUSE
```
