### ISSUE TITLE
Support for transactions

### ISSUE THREAD

**Issue by cecchisandrone** [edenhill/kafkacat#182]
Are Kafka transactions supported in producer / consumer? Is there a plan for that?

**Comment by edenhill** [comment]
Consumer transaction support is being worked on, Producer transactions will come later.
I'm curious though, how would you want to use transactions with kafkacat?

**Comment by cecchisandrone** [comment]
I need to test applications using Exactly-once, so the use of transactional-id for producers and isolation level read_committed for consumers.

**Comment by lij55** [comment]
> Consumer transaction support is being worked on, Producer transactions will come later.
> I'm curious though, how would you want to use transactions with kafkacat?

My use case is to simulate the 'rollback' operation for testing purposes to ensure the exactly once.

**Comment by edenhill** [comment]
I'm thinking all messages produced until EOF in input will be part of one single transaction, makes sense?

**Comment by YordanPavlov** [comment]
What is the state of isolation level support in Kcat consumer? In my use case I need to copy a Kafka topic between clusters. However the original producer does so using transactions, so Kcat needs to read with something like:
`--isolation-level=read_committed`
so that it does not read non-commited messages. Can I achieve this or possibly some work-around @edenhill ?

**Comment by edenhill** [comment]
isolation.level=read_committed is the default in librdkafka, and thus kcat.
Just make sure that your librdkafka version is recent enough to support consumer-side transactions (>1.2.0, but preferably latest release 1.8.2).
