### ISSUE TITLE
Connecting to a secure (TLS/SSL) schema registry that requires client authentication

### ISSUE THREAD

**Issue by teebee** [edenhill/kafkacat#198]
I can not figure out how to configure kafkacat to connect to a secure (TLS/SSL) schema registry that requires client authentication. Is that even possible?

**Comment by Liath** [comment]
So that works but if you're using Confluent's hosted Schema Registry it requires some trickery because the API keys Confluent issues are base64 strings and calls to the registry pass through libcurl which seems to be getting hung up on `/`s. I worked around this by generating keys until I got one without `/` in it but we should probably find a cleaner way to set credentials for this. 

It seems like curl assumes the first slash it encounters is the end of the hostname part of the URL:
```
$ curl 'https://test:tes/t@example.com'
curl: (3) Port number ended with 't'
```

**Comment by Liath** [comment]
encoding `/` as `%2F` seems to fix this

**Comment by edenhill** [comment]
This will need to be fixed in libserdes 
https://github.com/confluentinc/libserdes/issues/28
