### ISSUE TITLE
Is -J option supported?

### ISSUE THREAD

**Issue by kknd22** [edenhill/kafkacat#45]
(version 1.2.0) when I run:
$ kafkacat -b mybroker -t syslog -J

It gives me:
kafkacat: illegal option -- J

**Comment by edenhill** [comment]
I think your kafkacat failed to locate libyajl when it compiled, check the ./configure output.

If you want to build a statically linked kafkacat with JSON support you could run ./bootstrap.sh

**Comment by kknd22** [comment]
Thanks for the comments. I am on a mac. what's best way to install libyajl?
brew install kafkacat won't do it?

**Comment by fsaintjacques** [comment]
`brew install yajl`

**Comment by jsjohnst** [comment]
Rather than give ultimately unhelpful advice to someone, I fixed the problem:

https://github.com/Homebrew/homebrew/pull/48463

@kknd22 the PR above fixes your issue.
@edenhill If you are going to suggest folks to install via homebrew, you should make sure the package manager actually does the correct job of installing it, IMHO.

**Comment by edenhill** [comment]
Awesome @jsjohnst !

**Comment by jsjohnst** [comment]
@edenhill note to myself, don't comment on issues when I'm still stinging from being bitten by said issue. My sincere apologies for what easily could have been taken as an edgy tone.

**Comment by edenhill** [comment]
No worries!
I'm dont use OSX myself so I trust my users to supply and maintain support for it.
