### ISSUE TITLE
[Feature Request] Configure kafkacat to exit on broker connectivity errors

### ISSUE THREAD

**Issue by donatello** [edenhill/kafkacat#47]
While using kafkacat as a consumer or as a producer, it would be good if it's possible to have it quit with a non-zero exit status if there are broker related errors. Currently, in my testing as a consumer if there are broker connectivity errors after kafkacat starts consuming, it prints logs to stderr and appears to repeatedly retry.

Is this perhaps already possible to do?

**Comment by fsaintjacques** [comment]
You can technically do it with `librdkafka` configuration mechanism (see https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md). You'll have to define your own message/error callback in C, and probably pass your library with then LD_PRELOAD environment variable. After, all you have to do is call `kafkacat` with the `-X dr_msg_cb`. This is not the most elegant way to do it, but you can wrap it in a shell script.

**Comment by edenhill** [comment]
The above commit registers an error_cb to catch the ALL_BROKERS_DOWN error code from librdkafka, in which case kafkacat will exit.

This isn't perfect though since kafkacat is currently single-threaded and in producer mode it will block indefinately waiting for input on stdin (which there should typically be for a producer, so might not be a real problem).
Only when a message has been read from stdin will the error_cb be called.

The proper fix for this is for rdkafka to provide convenient auto-polling threads to alleviate this concern from simple programs, such as kafkacat.
