### ISSUE TITLE
kafkacat metadata does not display topic metadata

### ISSUE THREAD

**Issue by clescot** [edenhill/kafkacat#49]
when i execute  kafka-topics --describe  --zookeeper localhost --topic mytopic, it returnsPartitionCount:10	ReplicationFactor:1	Configs:cleanup.policy=compact .
it also display other details about leader and replicas:
Topic: myTopic	Partition: 0	Leader: 1	Replicas: 1	Isr: 1

it would be useful if kafkacat return this kind of details, especially the cleanup policy in case of log compaction usage.

best regards,

Charles.

**Comment by edenhill** [comment]
kafkacat currently does communicate with ZooKeeper at all, it uses the Kafka protocol for everything, including topic metadata. Unfortunately the Kafka protocol does not expose the topic configuration through its API and that's why kafkacat can't display it.

There is some work being done to expose a richer config retrieval API in the Kafka protocol but I'm not sure when it will be available - kafkacat will implement the corresponding support when it is though.

Maybe I'll get around to implementing zookeeper support in kafkacat some day so I'll leave this issue open as a feature request.

**Comment by clescot** [comment]
Hi,
why this issue has been closed?
does the issue has been fixed, or has been closed because it is impossible to do?

best regards,
Charles.

**Comment by edenhill** [comment]
Work is being done on [KIP-4](https://cwiki.apache.org/confluence/display/KAFKA/KIP-4+-+Command+line+and+centralized+administrative+operations) that provides a Kafka native API to cluster administration, rathern than going through ZK.
So I dont think it is meaningful to spend any time on adding ZK integration to kafkacat.

When KIP-4 is ready and support has been added to librdkafka it will be added to kafkacat aswell.
